import sys
import os
import platform
import ctypes
import numpy as np
from numba import cfunc, types, carray
from evaluation import evaluation_function

"""
-------------------------------
     DO NOT EDIT THIS FILE
-------------------------------
"""

COMPETITION_DEPTH = 5

# Returns: int32
# Args: int64* (pieces), int64* (occupancy), uint32 (side_to_move)
@cfunc(types.int32(types.CPointer(types.int64), types.CPointer(types.int64), types.uint32))
def evaluation_wrapper(board_pieces_ptr, board_occupancy_ptr, side_to_move):

    board_pieces = carray(board_pieces_ptr, (12,), np.int64)
    board_occupancy = carray(board_occupancy_ptr, (3,), np.int64)
    
    score = evaluation_function(board_pieces, board_occupancy, side_to_move)
    
    return np.int32(score)

def main():
    curr_dir = os.path.dirname(os.path.abspath(__file__))
    bindings_dir = os.path.join(curr_dir, "..", "bindings")

    system = sys.platform
    machine = platform.machine().lower()
    
    if system == "win32":
        lib_name = "ChessLib.dll"
    elif system == "linux":
        lib_name = "libChessLib.so"
    elif system == "darwin":
        if "arm64" in machine:
            lib_name = "libChessLib_arm64.dylib"
        else:
            lib_name = "libChessLib_intel.dylib"
            
        if not os.path.exists(os.path.join(bindings_dir, lib_name)):
             if os.path.exists(os.path.join(bindings_dir, "libChessLib.dylib")):
                 lib_name = "libChessLib.dylib"
    else:
        print(f"[Error] Unsupported OS: {system}")
        sys.exit(1)
        
    lib_path = os.path.join(curr_dir, "..", "bindings", lib_name)
    lib_path = os.path.abspath(lib_path)

    if not os.path.exists(lib_path):
        print(f"[Error] Shared library not found at: {lib_path}")
        print("Please ensure the correct binary for your OS is in the 'bindings/' folder.")
        sys.exit(1)

    try:
        chess_lib = ctypes.CDLL(lib_path)
    except OSError as e:
        print(f"[Error] Failed to load library: {e}")
        sys.exit(1)

    chess_lib.startEngine.argtypes = [ctypes.c_void_p, ctypes.c_int]
    
    print(f"--- Chess Engine Interface Loaded ---")
    print(f"Library: {lib_name}")
    
    engine_callback = evaluation_wrapper.address

    print(f"Starting Engine at Depth {COMPETITION_DEPTH}...")
    chess_lib.startEngine(engine_callback, COMPETITION_DEPTH)

if __name__ == "__main__":
    main()
